// <auto-generated />
using System;
using DataBaseGenerator.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBaseGenerator.Core.Migrations
{
    [DbContext(typeof(BaseGenerateContext))]
    [Migration("20220204122740_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("DataBaseGenerator.Core.Patient", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<int>("ID_Patient")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.HasKey("PatientID");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("DataBaseGenerator.Core.WorkList", b =>
                {
                    b.Property<int>("WorkListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirtProcedureStepStartDateTimehDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CompleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ID_Patient")
                        .HasColumnType("longtext");

                    b.Property<string>("Modality")
                        .HasColumnType("longtext");

                    b.Property<string>("PerformingPhysiciansName")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferringPhysiciansName")
                        .HasColumnType("longtext");

                    b.Property<string>("RequestingPhysician")
                        .HasColumnType("longtext");

                    b.Property<string>("SOPInstanceUID")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("StationAeTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("StudyDescription")
                        .HasColumnType("longtext");

                    b.HasKey("WorkListID");

                    b.ToTable("WorkList");
                });
#pragma warning restore 612, 618
        }
    }
}
